# Generated by Django 3.2 on 2025-01-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsuser',
            name='code',
            field=models.TextField(blank=True, verbose_name='Код'),
        ),
    ]
